package by.epam.task1.util;

public enum Parameter {
	NAME, PAYROLL, SAME_NET_PRICE, OTHER_NET_PRICE, LANDLINE_PRICE, INTERNET_PRICE, CONNECTION_FEE, FAVOUR_NUMBER, GROUP, MODEM_MODE, DAYS, REMAINING_RATE;
}
